### ISSUE TITLE
代码语法问题

### ISSUE THREAD

**Issue by iT-lijun** [ZHENFENG13/concurrent-programming#3]
0. src/chapter4/DeadLock.java代码片段
        DeadLock 哲学家A = new DeadLock(fork1);
        DeadLock 哲学家B = new DeadLock(fork2);
还有中文这种操作吗？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？
1. 同志麻烦自己先运行通过，再commit， OK？？？？？？？？？？？？？？？？？？？？？？？？

**Comment by ZHENFENG13** [comment]
Java支持中文类名、方法名、属性名，并且不会因为乱码问题导致运行期链接失败。这是Java内核支持UTF-8这一特性决定的。

编译可以通过的，还有，如果觉得命名方式有问题你自己改一下就好，很麻烦吗？
